// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_JTrbE6H-IYds6g2839wbECRM5Q9-6Go',
    appId: '1:483546832464:web:f1f8018e052c0cb2ddbb55',
    messagingSenderId: '483546832464',
    projectId: 'finanzas10c',
    authDomain: 'finanzas10c.firebaseapp.com',
    storageBucket: 'finanzas10c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7aZQtOTtTHQjZbn4Nk_OCYRdZXhxo1oo',
    appId: '1:483546832464:android:3a78b2959437d47addbb55',
    messagingSenderId: '483546832464',
    projectId: 'finanzas10c',
    storageBucket: 'finanzas10c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASAZWT-bmKboLbpco6ISAisKdgleTVUzc',
    appId: '1:483546832464:ios:73a7c0f0adc0946fddbb55',
    messagingSenderId: '483546832464',
    projectId: 'finanzas10c',
    storageBucket: 'finanzas10c.appspot.com',
    iosBundleId: 'com.example.finanzas10c',
  );

}