version: '2'
services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf_8c:/opt/sonarqube/conf
      - sonarqube_data_8c:/opt/sonarqube/data
      - sonarqube_extensions_8c:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins_8c:/opt/sonarqube/lib/bundled-plugins
  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql_8c:/var/lib/postgresql
      - postgresql_data_8c:/var/lib/postgresql/data
networks:
  sonarnet:
    driver: bridge
volumes:
  sonarqube_conf_8c:
  sonarqube_data_8c:
  sonarqube_extensions_8c:
  sonarqube_bundled-plugins_8c:
  postgresql_8c:
  postgresql_data_8c:

