// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkcaLbXJympLaI24KkcmLL1LMvfOufKGc',
    appId: '1:571319577284:web:694091108b5e920655f791',
    messagingSenderId: '571319577284',
    projectId: 'restaurantes-db5a5',
    authDomain: 'restaurantes-db5a5.firebaseapp.com',
    storageBucket: 'restaurantes-db5a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBotkGs11Zl5rYaSP_mW5hB31r14pR8wBU',
    appId: '1:571319577284:android:ab53c80c0b800d5455f791',
    messagingSenderId: '571319577284',
    projectId: 'restaurantes-db5a5',
    storageBucket: 'restaurantes-db5a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKhx1vY_825r1l5FrMUTC4oE2aeygk2BM',
    appId: '1:571319577284:ios:ae4404882c025ffa55f791',
    messagingSenderId: '571319577284',
    projectId: 'restaurantes-db5a5',
    storageBucket: 'restaurantes-db5a5.appspot.com',
    iosBundleId: 'com.example.learningLebc9c',
  );
}
