name: examen_u2_dmi
description: "Examen de Conocimientos de la Unidad #2 de la Materia Desarrollo Móvil Integral"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_rating: ^2.0.2
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  google_maps_flutter_web: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/

