// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn05Uu5MUL_a_tnrfgbYAsYJZjBV3tIMM',
    appId: '1:891067480882:web:6e92857a37cc2f98c2b52b',
    messagingSenderId: '891067480882',
    projectId: 'examenu2-6ba25',
    authDomain: 'examenu2-6ba25.firebaseapp.com',
    storageBucket: 'examenu2-6ba25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN2eUIaHVB15fw6SUzS8g9LHmxZKRgcVQ',
    appId: '1:891067480882:android:f7f33ffd0d6dc203c2b52b',
    messagingSenderId: '891067480882',
    projectId: 'examenu2-6ba25',
    storageBucket: 'examenu2-6ba25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw-ygo-g2NpdozrW6fDki21faA5H-9z4s',
    appId: '1:891067480882:ios:8bec1456e47847b2c2b52b',
    messagingSenderId: '891067480882',
    projectId: 'examenu2-6ba25',
    storageBucket: 'examenu2-6ba25.firebasestorage.app',
    iosBundleId: 'com.example.examenU2Dmi',
  );
}
