create database example1;

INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('1', 'address1', '1990-01-01', 'email1@example.com', 'John', 'Doe', 'John Doe');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('2', 'address2', '1991-02-02', 'email2@example.com', 'Jane', 'Smith', 'Jane Smith');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('3', 'address3', '1992-03-03', 'email3@example.com', 'Mike', 'Johnson', 'Mike Johnson');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('4', 'address4', '1993-04-04', 'email4@example.com', 'Sara', 'Williams', 'Sara Williams');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('5', 'address5', '1994-05-05', 'email5@example.com', 'David', 'Brown', 'David Brown');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('6', 'address6', '1995-06-06', 'email6@example.com', 'Emily', 'Jones', 'Emily Jones');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('7', 'address7', '1996-07-07', 'email7@example.com', 'Brian', 'Miller', 'Brian Miller');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('8', 'address8', '1997-08-08', 'email8@example.com', 'Laura', 'Taylor', 'Laura Taylor');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('9', 'address9', '1998-09-09', 'email9@example.com', 'Mark', 'Davis', 'Mark Davis');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('10', 'address10', '1999-10-10', 'email10@example.com', 'Melissa', 'Anderson', 'Melissa Anderson');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('11', 'address11', '2000-11-11', 'email11@example.com', 'Kevin', 'Moore', 'Kevin Moore');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('12', 'address12', '2001-12-12', 'email12@example.com', 'Hannah', 'White', 'Hannah White');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('13', 'address13', '2002-01-13', 'email13@example.com', 'Peter', 'Lee', 'Peter Lee');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('14', 'address14', '2003-02-14', 'email14@example.com', 'Sophia', 'Martin', 'Sophia Martin');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('15', 'address15', '2004-03-15', 'email15@example.com', 'Jason', 'Hall', 'Jason Hall');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('16', 'address16', '2005-04-16', 'email16@example.com', 'Eva', 'Clark', 'Eva Clark');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('17', 'address17', '2006-05-17', 'email17@example.com', 'Ryan', 'Lewis', 'Ryan Lewis');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('18', 'address18', '2007-06-18', 'email18@example.com', 'Olivia', 'Harris', 'Olivia Harris');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('19', 'address19', '2008-07-19', 'email19@example.com', 'Tom', 'Allen', 'Tom Allen');
INSERT INTO `example1`.`persona` (`id`, `address`, `birthday`, `email`, `firstname`, `lastname`, `name`) VALUES ('20', 'address20', '2009-08-20', 'email20@example.com', 'Emma', 'Turner', 'Emma Turner');